name: breview
description: A new Flutter application.

publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  image_picker: ^0.8.4+4
  firebase_storage: ^10.2.2
  firebase_core: ^1.10.4
  cloud_firestore: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
