name: breview
description: A new Flutter application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.10.0
  image_picker: ^0.8.4+4
  cloud_firestore: ^2.5.1
  firebase_storage: ^10.2.3
  firebase_auth: ^3.3.3
  cupertino_icons: ^1.0.4
  pinput: ^1.2.2
  provider: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
